### ISSUE TITLE
Duplicate key for form_drafts

### ISSUE THREAD

**Issue by werebus** [umts/ft-forms#16]
Hey it's our first bug!

An ActiveRecord::RecordNotUnique occurred in form_drafts#new:

```
  Mysql::Error: Duplicate entry '1' for key 'PRIMARY': INSERT INTO `form_drafts` (`id`, `name`, `created_at`, `updated_at`, `user_id`, `form_id`) VALUES (?, ?, ?, ?, ?, ?)
  app/models/form.rb:15:in `create_draft'
```

-------------------------------
Request:
-------------------------------

  * URL        : https://ft-forms.admin.umass.edu/form_drafts/new?form_id=1
  * HTTP Method: GET
  * IP address : REDACTED
  * Parameters : {"form_id"=>"1", "controller"=>"form_drafts", "action"=>"new"}
  * Timestamp  : 2015-07-16 15:51:12 -0400
  * Server : af-transit-app3.admin.umass.edu
  * Rails root : /srv/ft-forms/releases/20150716183935
  * Process: 4903

-------------------------------
Backtrace:
-------------------------------

```
  app/models/form.rb:15:in `create_draft'
  app/controllers/form_drafts_controller.rb:16:in `new'
```

**Comment by werebus** [comment]
This is because of [this line][1].  `attributes` includes the `Form`'s id, so it tries to explicitly set the `FormDraft` id to be the same as its `Form` instead of letting the auto-number do its job, which only works once per `Form` before breaking in this manner.

[1]: https://github.com/umts/ft-forms/blob/4b47ae41f68478ba4ee98b337de73de979f4d153/app/models/form.rb#L14

**Comment by werebus** [comment]
adding an `{id: nil}` into that hash should do it, I think.

**Comment by dfaulken** [comment]
`attributes.except(:id).merge` etc. is cleaner.

**Comment by werebus** [comment]
Agreed.  And communicates intention a bit better.

**Comment by dfaulken** [comment]
Build passes; deploying
