### ISSUE TITLE
Sending email

### ISSUE THREAD

**Issue by werebus** [umts/ft-forms#20]
Mail messages have to be "delivered" as well.  That is:

```ruby
FtFormsMailer.send_form responses
```

should be 

```ruby
FtFormsMailer.send_form(responses).deliver
```

I guess?  Of course, that actually breaks the specs.  This is because the mailer methods don't actually [`return true`][1], they return an `ActionMailer::MessageDelivery` object.  But I'm bad at mocks...

[1]:  https://github.com/umts/ft-forms/blob/01b6a0585cdf1062b4c5d17d877a2a40825b2aa8/spec/controllers/forms_controller_spec.rb#L117

**Comment by dfaulken** [comment]
Whoops. I'll look into this.
