### ISSUE TITLE
Write tests to make sure you can add comma-separated email addresses

### ISSUE THREAD

**Issue by Anbranin** [umts/ft-forms#35]
It'd be nice to be able to change the form destination to have two email addresses.

**Comment by werebus** [comment]
Should be comma-separated, per RFC 2822.  Outlook uses semicolons, but
they're the only ones. I suspect that a comma-separated list of email
addresses might "just work."

http://cr.yp.to/immhf/recip.html

**Comment by werebus** [comment]
I tried it locally just now, and things look fine to me:

```
FtFormsMailer#send_form: processed outbound mail in 153.6ms

Sent mail to me@example.com, you@example.com (11.8ms)
Date: Thu, 20 Aug 2015 09:35:39 -0400
From: transit-it@admin.umass.edu
To: me@example.com, 
 you@example.com
Message-ID: <55d5d7ab95d33_c0d3f852163f9582278c@umts-sp3-2.mail>
Subject: New Meet & Greet Request
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello,

A new Meet & Greet request has been received:
```

Of course there's #34, so I had to use the console to get the address to be that.
