### ISSUE TITLE
Configurable reply-to address

### ISSUE THREAD

**Issue by dfaulken** [umts/ft-forms#39]
In a similar vein to #4, and prompted by #31, it'd be nice if folks could configure a reply-to address for a form.

**Comment by akaplo** [comment]
What would be the scenario where we want the reply-to to be configured as something other than the default?

<b>Example</b> Default is <code>transit-it@umass</code>, but a staff member (say the FT supervisor) is logged in and they create a new form.  The form includes a field called "address for form submitters to reply to," and the form create-er puts his/her address.  So, when someone submits a form, the confirmation email that they get will have a reply-to value of [that supervisor's email that they put into the field].  Yes?

**Comment by dfaulken** [comment]
Correct.

**Comment by akaplo** [comment]
Awesome. So this would be a form_draft related thing, then?  Also remember the other day when we booted the server and tried to click New Form and it didn't work?  That's still a thing..

**Comment by werebus** [comment]
Just noticed that this is a required field.  Should it be?

**Comment by dfaulken** [comment]
Good catch - @akaplo, we can remove [this line](https://github.com/akaplo/ft-forms/blob/c1a461e154b24adac6741ad2091e1710f4eab54c/app/views/form_drafts/edit.haml#L14).
