### ISSUE TITLE
Email formatting request

### ISSUE THREAD

**Issue by werebus** [umts/ft-forms#46]
>  When receiving M&G requests to the front desk email, it would be really nice if different sections were separated from each other. So, for example the sections could be:

>  Contact information

>  Passenger information

>  Arrival

>  Departure.

>  Having the information come in one big block makes it a little harder for me to pull information out of it when I'm looking back and forth from one screen to another.

**Comment by dfaulken** [comment]
Any suggestions on how to do this from a dynamic form?

Perhaps a line break wherever there's supposed to be a heading?
