### ISSUE TITLE
Some Rubocop cleanup?

### ISSUE THREAD

**Issue by dfaulken** [umts/ft-forms#78]
It might be nice to provide comments in the `.rubocop.yml` file explaining why we think particular cops deserve to be excluded from the entire app (or however it is that they're configured). For instance, there's a difference between "we think this style preference is wrong for all of Ruby, and here's why" versus "we think this style preference doesn't apply *in this common scenario*, and here's why" as far as indicating to new ft-forms developers what's okay and what's not.

Also, there is an unused `.rubocop_todo.yml` file in master. Sort of confusing to have a file of that nature in version control if it's unused - I'd recommend either `.gitignore`-ing it entirely and removing it, or just removing it now and being vigilant about not including it in future PRs. (At the time I included it, it was because it *was* used, but with CodeClimate we've moved away from that particular workflow, I believe.)

**Comment by werebus** [comment]
Closed in #159
